name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    name: Build with JDK ${{matrix.java.version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [
          { 'version': '21' }
        ]

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install Podman using Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install podman
          podman --version

      - uses: actions/setup-java@v4
        name: Set up JDK ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B spotless:check verify